import base64
import logging
import math
import re
import tempfile
import wave
from concurrent.futures import ThreadPoolExecutor, as_completed
from dataclasses import dataclass
from pathlib import Path
from typing import Callable

import requests

from app.core.config import settings
from app.services.transcription_service import (
    TranscriptionResult,
    TranscriptionSegmentData,
)


logger = logging.getLogger(__name__)
ProgressCallback = Callable[[int], None]


@dataclass(frozen=True)
class CloudflareChunk:
    index: int
    core_start: float
    core_end: float
    extract_start: float
    extract_end: float
    file_path: Path


def _validate_cloudflare_settings() -> None:
    if not settings.cloudflare_account_id.strip():
        raise RuntimeError(
            "CLOUDFLARE_ACCOUNT_ID is not configured."
        )

    if not settings.cloudflare_api_token.strip():
        raise RuntimeError(
            "CLOUDFLARE_API_TOKEN is not configured."
        )

    if not settings.cloudflare_whisper_model.strip():
        raise RuntimeError(
            "CLOUDFLARE_WHISPER_MODEL is not configured."
        )

    if settings.cloudflare_chunk_seconds <= 0:
        raise ValueError(
            "CLOUDFLARE_CHUNK_SECONDS must be greater than 0."
        )

    if settings.cloudflare_chunk_overlap_seconds < 0:
        raise ValueError(
            "CLOUDFLARE_CHUNK_OVERLAP_SECONDS cannot be negative."
        )

    if (
        settings.cloudflare_chunk_overlap_seconds
        >= settings.cloudflare_chunk_seconds
    ):
        raise ValueError(
            "CLOUDFLARE_CHUNK_OVERLAP_SECONDS must be "
            "smaller than CLOUDFLARE_CHUNK_SECONDS."
        )

    if settings.cloudflare_parallel_workers <= 0:
        raise ValueError(
            "CLOUDFLARE_PARALLEL_WORKERS must be greater than 0."
        )


def _get_wav_duration(source: Path) -> float:
    try:
        with wave.open(str(source), "rb") as wav_file:
            frame_count = wav_file.getnframes()
            sample_rate = wav_file.getframerate()

            if frame_count <= 0 or sample_rate <= 0:
                raise ValueError(
                    "The normalized WAV has invalid audio metadata."
                )

            return frame_count / float(sample_rate)

    except wave.Error as exc:
        raise ValueError(
            "Cloudflare transcription requires the "
            "normalized PCM WAV generated by the audio pipeline."
        ) from exc


def _write_wav_slice(
    source: Path,
    destination: Path,
    start_seconds: float,
    end_seconds: float,
) -> None:
    if end_seconds <= start_seconds:
        raise ValueError(
            "Invalid Cloudflare audio chunk interval."
        )

    try:
        with wave.open(str(source), "rb") as input_wav:
            channels = input_wav.getnchannels()
            sample_width = input_wav.getsampwidth()
            sample_rate = input_wav.getframerate()
            compression_type = input_wav.getcomptype()

            if compression_type != "NONE":
                raise ValueError(
                    "The normalized WAV must use uncompressed PCM."
                )

            start_frame = max(
                0,
                int(round(start_seconds * sample_rate)),
            )
            end_frame = min(
                input_wav.getnframes(),
                int(round(end_seconds * sample_rate)),
            )
            frame_count = max(0, end_frame - start_frame)

            if frame_count <= 0:
                raise ValueError(
                    "Cloudflare audio chunk contains no samples."
                )

            input_wav.setpos(start_frame)
            frames = input_wav.readframes(frame_count)

        with wave.open(str(destination), "wb") as output_wav:
            output_wav.setnchannels(channels)
            output_wav.setsampwidth(sample_width)
            output_wav.setframerate(sample_rate)
            output_wav.setcomptype("NONE", "not compressed")
            output_wav.writeframes(frames)

    except wave.Error as exc:
        raise ValueError(
            "Could not split normalized WAV for "
            "Cloudflare transcription."
        ) from exc


def _build_chunks(
    source: Path,
    temp_directory: Path,
    duration: float,
) -> list[CloudflareChunk]:
    chunk_seconds = float(settings.cloudflare_chunk_seconds)
    overlap_seconds = float(
        settings.cloudflare_chunk_overlap_seconds
    )

    chunk_count = max(
        1,
        math.ceil(duration / chunk_seconds),
    )

    chunks: list[CloudflareChunk] = []

    for index in range(chunk_count):
        core_start = index * chunk_seconds
        core_end = min(
            duration,
            core_start + chunk_seconds,
        )

        extract_start = max(
            0.0,
            core_start - overlap_seconds,
        )
        extract_end = min(
            duration,
            core_end + overlap_seconds,
        )

        destination = (
            temp_directory / f"chunk_{index:04d}.wav"
        )

        _write_wav_slice(
            source,
            destination,
            extract_start,
            extract_end,
        )

        chunks.append(
            CloudflareChunk(
                index=index,
                core_start=core_start,
                core_end=core_end,
                extract_start=extract_start,
                extract_end=extract_end,
                file_path=destination,
            )
        )

    return chunks


def _parse_timestamp(value: str) -> float:
    cleaned = value.strip().replace(",", ".")
    parts = cleaned.split(":")

    if len(parts) == 3:
        hours = float(parts[0])
        minutes = float(parts[1])
        seconds = float(parts[2])
        return hours * 3600 + minutes * 60 + seconds

    if len(parts) == 2:
        minutes = float(parts[0])
        seconds = float(parts[1])
        return minutes * 60 + seconds

    raise ValueError(
        f"Unsupported VTT timestamp: {value}"
    )


def _parse_vtt(
    vtt_text: str,
) -> list[TranscriptionSegmentData]:
    if not vtt_text.strip():
        return []

    normalized = (
        vtt_text.replace("\r\n", "\n").replace("\r", "\n")
    )

    blocks = re.split(
        r"\n\s*\n",
        normalized.strip(),
    )

    timestamp_pattern = re.compile(
        r"(?P<start>\d{1,2}:\d{2}(?::\d{2})?[.,]\d{3})"
        r"\s*-->\s*"
        r"(?P<end>\d{1,2}:\d{2}(?::\d{2})?[.,]\d{3})"
    )

    segments: list[TranscriptionSegmentData] = []

    for block in blocks:
        lines = [
            line.strip()
            for line in block.splitlines()
            if line.strip()
        ]

        match = None
        timing_index = None

        for index, line in enumerate(lines):
            candidate = timestamp_pattern.search(line)

            if candidate is not None:
                match = candidate
                timing_index = index
                break

        if match is None or timing_index is None:
            continue

        text_lines = lines[timing_index + 1:]
        cleaned_text = " ".join(text_lines).strip()
        cleaned_text = re.sub(
            r"<[^>]+>",
            "",
            cleaned_text,
        ).strip()

        if not cleaned_text:
            continue

        start_time = _parse_timestamp(
            match.group("start")
        )
        end_time = _parse_timestamp(
            match.group("end")
        )

        if end_time <= start_time:
            continue

        segments.append(
            TranscriptionSegmentData(
                start_time=start_time,
                end_time=end_time,
                text=cleaned_text,
            )
        )

    return segments


def _segments_from_json(
    raw_segments: object,
) -> list[TranscriptionSegmentData]:
    if not isinstance(raw_segments, list):
        return []

    parsed: list[TranscriptionSegmentData] = []

    for item in raw_segments:
        if not isinstance(item, dict):
            continue

        start_value = (
            item.get("start")
            if item.get("start") is not None
            else item.get("start_time")
        )
        end_value = (
            item.get("end")
            if item.get("end") is not None
            else item.get("end_time")
        )
        text_value = (
            item.get("text")
            or item.get("transcript")
        )

        try:
            start_time = float(start_value)
            end_time = float(end_value)
        except (TypeError, ValueError):
            continue

        if not isinstance(text_value, str):
            continue

        cleaned_text = text_value.strip()

        if not cleaned_text or end_time <= start_time:
            continue

        parsed.append(
            TranscriptionSegmentData(
                start_time=start_time,
                end_time=end_time,
                text=cleaned_text,
            )
        )

    return parsed


def _cloudflare_endpoint() -> str:
    base_url = settings.cloudflare_ai_base_url.rstrip("/")

    if not base_url:
        raise RuntimeError(
            "Cloudflare Workers AI base URL "
            "could not be constructed."
        )

    model = settings.cloudflare_whisper_model.strip()

    return f"{base_url}/{model}"


def _request_chunk(
    chunk: CloudflareChunk,
) -> tuple[
    CloudflareChunk,
    list[TranscriptionSegmentData],
    str | None,
]:
    audio_bytes = chunk.file_path.read_bytes()
    audio_base64 = base64.b64encode(
        audio_bytes
    ).decode("ascii")

    payload: dict[str, object] = {
        "audio": audio_base64,
        "task": "transcribe",
        "vad_filter": (
            settings.cloudflare_whisper_vad_filter
        ),
        "beam_size": (
            settings.cloudflare_whisper_beam_size
        ),
        "condition_on_previous_text": (
            settings
            .cloudflare_whisper_condition_on_previous_text
        ),
    }

    language = settings.cloudflare_whisper_language.strip()

    if language:
        payload["language"] = language

    initial_prompt = (
        settings.cloudflare_whisper_initial_prompt.strip()
    )

    if initial_prompt:
        payload["initial_prompt"] = initial_prompt

    try:
        response = requests.post(
            _cloudflare_endpoint(),
            headers={
                "Authorization": (
                    "Bearer "
                    + settings.cloudflare_api_token.strip()
                ),
                "Content-Type": "application/json",
            },
            json=payload,
            timeout=settings.cloudflare_timeout_seconds,
        )

    except requests.RequestException as exc:
        raise RuntimeError(
            "Cloudflare transcription request failed."
        ) from exc

    if not response.ok:
        detail = response.text.strip()

        if len(detail) > 1000:
            detail = detail[:1000] + "..."

        raise RuntimeError(
            "Cloudflare transcription returned "
            f"HTTP {response.status_code}. {detail}"
        )

    try:
        envelope = response.json()
    except ValueError as exc:
        raise RuntimeError(
            "Cloudflare returned an invalid JSON response."
        ) from exc

    if not isinstance(envelope, dict):
        raise RuntimeError(
            "Cloudflare returned an unexpected response."
        )

    if envelope.get("success") is False:
        raise RuntimeError(
            "Cloudflare transcription was unsuccessful. "
            f"Errors: {envelope.get('errors')}"
        )

    result = envelope.get("result")

    if not isinstance(result, dict):
        raise RuntimeError(
            "Cloudflare response did not contain "
            "a transcription result."
        )

    segments = _segments_from_json(
        result.get("segments")
    )

    if not segments:
        segments = _parse_vtt(
            str(result.get("vtt") or "")
        )

    if not segments:
        text_value = result.get("text")

        if isinstance(text_value, str):
            cleaned_text = text_value.strip()

            if cleaned_text:
                segments = [
                    TranscriptionSegmentData(
                        start_time=0.0,
                        end_time=max(
                            0.001,
                            chunk.extract_end
                            - chunk.extract_start,
                        ),
                        text=cleaned_text,
                    )
                ]

    if not segments:
        raise ValueError(
            "Cloudflare did not return any speech "
            "for this audio chunk."
        )

    language_value: str | None = None

    transcription_info = result.get(
        "transcription_info"
    )

    if isinstance(transcription_info, dict):
        detected_language = (
            transcription_info.get("language")
            or transcription_info.get(
                "detected_language"
            )
        )

        if isinstance(detected_language, str):
            language_value = (
                detected_language.strip()
                or None
            )

    if language_value is None:
        direct_language = result.get("language")

        if isinstance(direct_language, str):
            language_value = (
                direct_language.strip()
                or None
            )

    return chunk, segments, language_value


def _belongs_to_core(
    segment: TranscriptionSegmentData,
    chunk: CloudflareChunk,
    duration: float,
) -> bool:
    global_start = (
        chunk.extract_start
        + segment.start_time
    )
    global_end = (
        chunk.extract_start
        + segment.end_time
    )
    midpoint = (
        global_start + global_end
    ) / 2.0

    is_last = (
        chunk.core_end
        >= duration - 0.001
    )

    if is_last:
        return (
            midpoint >= chunk.core_start
            and midpoint <= duration + 0.5
        )

    return (
        midpoint >= chunk.core_start
        and midpoint < chunk.core_end
    )


def _to_global_segment(
    segment: TranscriptionSegmentData,
    chunk: CloudflareChunk,
    duration: float,
) -> TranscriptionSegmentData:
    start_time = max(
        0.0,
        chunk.extract_start
        + segment.start_time,
    )
    end_time = min(
        duration,
        chunk.extract_start
        + segment.end_time,
    )

    return TranscriptionSegmentData(
        start_time=start_time,
        end_time=max(start_time, end_time),
        text=segment.text,
    )


def _remove_near_duplicate_segments(
    segments: list[TranscriptionSegmentData],
) -> list[TranscriptionSegmentData]:
    if not segments:
        return []

    ordered = sorted(
        segments,
        key=lambda item: (
            item.start_time,
            item.end_time,
        ),
    )

    cleaned: list[TranscriptionSegmentData] = []

    for segment in ordered:
        if not cleaned:
            cleaned.append(segment)
            continue

        previous = cleaned[-1]

        same_text = (
            previous.text.strip().casefold()
            == segment.text.strip().casefold()
        )
        close_in_time = (
            abs(
                previous.start_time
                - segment.start_time
            )
            <= 2.0
        )

        if same_text and close_in_time:
            if segment.end_time > previous.end_time:
                cleaned[-1] = segment
            continue

        cleaned.append(segment)

    return cleaned


def transcribe_audio_cloudflare(
    audio_path: str | Path,
    *,
    progress_callback: ProgressCallback | None = None,
) -> TranscriptionResult:
    """
    Transcribe normalized audio with Cloudflare Workers AI.

    This keeps English, Urdu and mixed-language meetings
    supported by omitting the language hint unless explicitly
    configured.

    Real progress is based on completed cloud transcription
    chunks, not a fake timer.
    """

    _validate_cloudflare_settings()

    source = Path(audio_path).resolve()

    if not source.exists():
        raise FileNotFoundError(
            "Normalized meeting audio does not exist."
        )

    if not source.is_file():
        raise ValueError(
            "The transcription source is not a valid file."
        )

    if source.stat().st_size == 0:
        raise ValueError(
            "The transcription source is empty."
        )

    duration = _get_wav_duration(source)
    last_reported = -1

    def report(value: int) -> None:
        nonlocal last_reported

        if progress_callback is None:
            return

        bounded = max(
            0,
            min(100, int(value)),
        )

        if bounded == last_reported:
            return

        last_reported = bounded
        progress_callback(bounded)

    report(0)

    with tempfile.TemporaryDirectory(
        prefix="meeting-intelligence-cloudflare-"
    ) as temp_dir:
        chunks = _build_chunks(
            source,
            Path(temp_dir),
            duration,
        )

        chunk_results: dict[
            int,
            tuple[
                CloudflareChunk,
                list[TranscriptionSegmentData],
                str | None,
            ],
        ] = {}

        completed = 0

        max_workers = min(
            max(
                1,
                settings.cloudflare_parallel_workers,
            ),
            len(chunks),
        )

        with ThreadPoolExecutor(
            max_workers=max_workers
        ) as executor:
            futures = {
                executor.submit(
                    _request_chunk,
                    chunk,
                ): chunk
                for chunk in chunks
            }

            for future in as_completed(futures):
                chunk = futures[future]

                try:
                    result = future.result()
                except Exception:
                    logger.exception(
                        "Cloudflare transcription failed "
                        "for chunk %s.",
                        chunk.index,
                    )
                    raise

                chunk_results[
                    chunk.index
                ] = result

                completed += 1

                report(
                    round(
                        completed
                        / len(chunks)
                        * 100
                    )
                )

        merged_segments: list[
            TranscriptionSegmentData
        ] = []
        detected_languages: list[str] = []

        for chunk_index in sorted(chunk_results):
            (
                chunk,
                local_segments,
                detected_language,
            ) = chunk_results[chunk_index]

            if (
                detected_language
                and detected_language
                not in detected_languages
            ):
                detected_languages.append(
                    detected_language
                )

            for local_segment in local_segments:
                if not _belongs_to_core(
                    local_segment,
                    chunk,
                    duration,
                ):
                    continue

                global_segment = _to_global_segment(
                    local_segment,
                    chunk,
                    duration,
                )

                if (
                    global_segment.end_time
                    <= global_segment.start_time
                ):
                    continue

                merged_segments.append(
                    global_segment
                )

    merged_segments = _remove_near_duplicate_segments(
        merged_segments
    )

    if not merged_segments:
        raise ValueError(
            "Cloudflare did not detect any speech "
            "in the recording."
        )

    configured_language = (
        settings.cloudflare_whisper_language.strip()
    )

    if configured_language:
        language = configured_language
    elif len(detected_languages) == 1:
        language = detected_languages[0]
    elif len(detected_languages) > 1:
        language = "multilingual"
    else:
        language = None

    report(100)

    return TranscriptionResult(
        language=language,
        language_probability=None,
        duration=duration,
        segments=merged_segments,
    )
